---
title: "Creation de la BDD coposite"
format: html
---

Import des BDD
```{r}
library(tidyverse)
setwd("C:/Users/Tibo/Documents/Demographie/M2S1/UE4 - Traitement de données/traitement-donnee-systeme-soin")

DK06 <- read_csv("data/DK/DK_2006p_EUSILC.csv")
DK07 <- read_csv("data/DK/DK_2007p_EUSILC.csv")
DK08 <- read_csv("data/DK/DK_2008p_EUSILC.csv")
DK09 <- read_csv("data/DK/DK_2009p_EUSILC.csv")
DK10 <- read_csv("data/DK/DK_2010p_EUSILC.csv")
DK11 <- read_csv("data/DK/DK_2011p_EUSILC.csv")
DK12 <- read_csv("data/DK/DK_2012p_EUSILC.csv")
DK13 <- read_csv("data/DK/DK_2013p_EUSILC.csv")

AT06 <- read_csv("data/AT/AT_2006p_EUSILC.csv")
AT07 <- read_csv("data/AT/AT_2007p_EUSILC.csv")
AT08 <- read_csv("data/AT/AT_2008p_EUSILC.csv")
AT09 <- read_csv("data/AT/AT_2009p_EUSILC.csv")
AT10 <- read_csv("data/AT/AT_2010p_EUSILC.csv")
AT11 <- read_csv("data/AT/AT_2011p_EUSILC.csv")
AT12 <- read_csv("data/AT/AT_2012p_EUSILC.csv")
AT13 <- read_csv("data/AT/AT_2013p_EUSILC.csv")
```

On garde les variables suivantes : 
DB020 : Pays de résidence
DB010 : Année d'enquête
HS060 : Capacité à faire face a une dépense imprévue
HS101 : Capacité à subvenir à ces besoins
HI010 : Evolution dans les revenus du foyer par rapport à l'année précédente
HI020 : Raison de l'augmentation
HI030 : Raison de la diminution
RB090 : Sexe
RB060 : Poids personnel de BDD
RB062 : Poids longitudinal (2 ans)
RB063 : Poids longitudinal (3 ans)
RB064 : Poids longitudinal (4 ans)
RB065 : Poids longitudinal (5 ans)
RB066 : Poids longitudinal (6 ans)
RB080 : Année de naissance
RB082 : age en années révolues
PB190 : Statut marital
PE041 : Niveau d'étude
PH010 : Etat de santé ressenti
PH020 : Souffre d'une maladie chronique
PH030 : Limitation des activités à cause de la santé
PH040 : Non recours au soin
PH050 : Raison du non recours au soin
PH060 : Non recours au soin dentaire
PH070 : Raison du non recours au soin dentaire
PW010 : Sentiment de statisfaction dans la vie


